-- 코드를 입력하세요
WITH M AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO 
    GROUP BY FOOD_TYPE
)
SELECT I.FOOD_TYPE, REST_ID, REST_NAME, M.FAVORITES
FROM REST_INFO AS I
INNER JOIN M
ON I.FOOD_TYPE = M.FOOD_TYPE AND I.FAVORITES = M.FAVORITES
ORDER BY I.FOOD_TYPE DESC
