-- 코드를 입력하세요
WITH A AS (
    SELECT WRITER_ID, COUNT(*) AS CNT
    FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID
    HAVING CNT >= 3
)
SELECT 
    USER_ID, 
    NICKNAME, 
    CONCAT_WS(' ', CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS 전체주소, 
    CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_USER AS U
INNER JOIN A
ON U.USER_ID = A.WRITER_ID
ORDER BY U.USER_ID DESC