-- 코드를 입력하세요
WITH RECURSIVE T1 AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM T1
    WHERE HOUR < 23
), H AS (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS `COUNT`
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
    ORDER BY HOUR(DATETIME)
)
SELECT 
    T1.HOUR, 
    CASE
        WHEN H.COUNT IS NULL THEN 0
        ELSE H.COUNT
    END AS `COUNT`
FROM T1
LEFT JOIN H
ON T1.HOUR = H.HOUR
UNION
SELECT 
    T1.HOUR, 
    CASE
        WHEN H.COUNT IS NULL THEN 0
        ELSE H.COUNT
    END AS `COUNT`
FROM T1 
RIGHT JOIN H
ON T1.HOUR = H.HOUR
ORDER BY HOUR