-- 코드를 입력하세요
WITH T AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD AS B
    WHERE `STATUS` = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
)
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM T
INNER JOIN USED_GOODS_USER AS U
ON T.WRITER_ID = U.USER_ID
ORDER BY TOTAL_SALES ASC
