-- 코드를 작성해주세요
WITH R_P_ITEM AS (
    SELECT T.PARENT_ITEM_ID, T.ITEM_ID
    FROM ITEM_INFO AS I
    LEFT JOIN ITEM_TREE AS T
    ON I.ITEM_ID = T.PARENT_ITEM_ID
    WHERE RARITY = 'RARE'
)
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I, R_P_ITEM AS R
WHERE I.ITEM_ID = R.ITEM_ID
ORDER BY I.ITEM_ID DESC
