-- 코드를 작성해주세요
WITH P AS (
    SELECT ID, GENOTYPE
    FROM ECOLI_DATA 
)
SELECT E.ID, E.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS E
LEFT OUTER JOIN P
ON E.PARENT_ID = P.ID
WHERE E.GENOTYPE & (P.GENOTYPE) = P.GENOTYPE
ORDER BY ID ASC
