-- 코드를 입력하세요
WITH TABLE_H AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE start_date>="2022-08-01" and start_date<"2022-11-01"
), TABLE_CNT AS (
    SELECT CAR_ID, COUNT(*) AS CNT
    FROM TABLE_H
    GROUP BY CAR_ID
    HAVING CNT >= 5
)
SELECT MONTH(start_date) AS MONTH, TABLE_H.CAR_ID AS CAR_ID, COUNT(*) AS RECORDS
FROM TABLE_H
INNER JOIN TABLE_CNT
ON TABLE_H.CAR_ID = TABLE_CNT.CAR_ID
GROUP BY MONTH(start_date), car_id
HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC