-- 코드를 작성해주세요
WITH Y AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS B
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
), E AS (
SELECT *, YEAR(DIFFERENTIATION_DATE) AS YEAR
FROM ECOLI_DATA
)
SELECT E.YEAR, (Y.B - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM E 
INNER JOIN Y
ON E.YEAR = Y.YEAR
ORDER BY E.YEAR ASC, YEAR_DEV ASC