-- 코드를 작성해주세요
WITH S AS (
    SELECT ID, FISH_NAME, LENGTH
    FROM FISH_INFO AS I
    INNER JOIN FISH_NAME_INFO AS N
    ON I.FISH_TYPE = N.FISH_TYPE
), A AS (
    SELECT FISH_NAME, MAX(LENGTH) AS LENGTH
    FROM S
    GROUP BY FISH_NAME
)
SELECT ID, S.FISH_NAME, S.LENGTH
FROM S
INNER JOIN A
ON S.FISH_NAME = A.FISH_NAME AND
S.LENGTH = A.LENGTH