-- 코드를 작성해주세요
WITH S AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE 
    GROUP BY EMP_NO, YEAR
    ORDER BY SUM(SCORE) DESC
    LIMIT 1
)
SELECT S.SCORE, E.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES AS E, S
WHERE E.EMP_NO = S.EMP_NO