-- 코드를 입력하세요
WITH S AS (
    SELECT *
    FROM BOOK_SALES 
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
)
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM S
INNER JOIN BOOK AS B
ON S.BOOK_ID = B.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY ASC