-- 코드를 입력하세요
WITH M AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY REGEXP '과자|국|김치|식용유'
    GROUP BY CATEGORY
)
SELECT M.CATEGORY, M.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F, M
WHERE F.CATEGORY = M.CATEGORY AND F.PRICE = M.MAX_PRICE
ORDER BY MAX_PRICE DESC